# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e9ad9841ceca415a35c4f87cac105d93632084df0c14ced8e44854043b7a7b145000da09b8668bb9038de3092ac15fbc23a348e5b357cbc168713f2658cbe592

test:
  secret_key_base: d589e029c7521c58f3b6ce021bf67791b6a8d7dabcdb1ca09bca83e996e92459dc10bbc64c1b5827f599d7f8db63efd2a1c82983b1dbaf842d6d89ff83dd1f8f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
